# Providing rolling update strategy
# Here ReplicaSet is enwrapped into deployment like, containers wrapped --> into pod 
# ReplicatSet managed the deployment, here i am copyin the whole rs-manifest.yml file into deployment-manifest.yml
apiVersion: apps/V1
kind: Deployment
metadata:
  name: web-eb-ms-deployment
  labels:
    app: web-ms-app
# here we didn't specify the namespace, get default
spec:  # we specify the pods, pods template.
  replicas: 3 # creating the 3 replica of pod
  selector:  # here we mention the label to refer the pod
    matchLabels:
      app: web-ms-app
  template: #so I directly copy the pods details from pod-manifest.yml file, from metadata
    metadata: 
        # name: eb-ms-pod
        labels: 
          env: uat-env
          app: web-ms-app 
        # namespace: uat
    spec: 
      containers:
        - name: web-eb-ms-nginx-instance
          image: nginx
          ports:
            - name: http
              containerPort: 80
            # - name: eb-tomcat-instance
            #   image: tomcat
            #   ports:
            #     - name: java
            #       containerPort: 8080
# now, on that pod we need a svc-manifest.yml fil because we need to expose the svc
...

---
# copying svc-manifest.yml file
# svc-manifest for NodePort
apiVersion: v1
kind: Service
metadata:
  name: web-eb-ms-pod-service
  labels:
    env: uat-env
    app: eb-ms-app 
  # namespace: uat #<ns-name>
spec:
  type: NodePort
  selector:
    app: eb-ms-app #[app: eb-ms-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: http
    #   protocol: TCP
    #   port: 8080
    #   targetPort: 8080
...