# Providing rolling update strategy
# Here ReplicaSet is enwrapped into deployment like, containers wrapped --> into pod 
# ReplicatSet managed the deployment, here i am copyin the whole rs-manifest.yml file into deployment-manifest.yml
apiVersion: apps/V1
kind: Deployment
metadata:
  name: web-eb-ms-deployment
  labels:
    app: web-ms-app
# here we didn't specify the namespace, get default
spec:  # we specify the pods, pods template.
  replicas: 3 # creating the 3 replica of pod
  selector:  # here we mention the label to refer the pod
    matchLabels:
      app: bgmi-ms-app
  template: #so I directly copy the pods details from pod-manifest.yml file, from metadata
    metadata: 
        # name: eb-ms-pod
        labels: 
          env: uat-env
          app: bgmi-ms-app 
        # namespace: uat
    spec: 
      containers:
        - name: eb-ms-nginx-instance
          image: nginx
          ports:
            - name: http
              containerPort: 80
            # - name: eb-tomcat-instance
            #   image: tomcat
            #   ports:
            #     - name: java
            #       containerPort: 8080
# now, on that pod we need a svc-manifest.yml fil because we need to expose the svc
...