apiVersion: v1
kind: Pod
metadata: 
    name: eb-ms-pod
    labels: 
      env: UAT-env
      app: eb-ms-app
    namespace: prod
spec: 
  containers:
    - name: eb-ms-instance
      image: nginx
      ports:
        - name: http
          container
