apiVersion: v1
kind: Service
metadata:
  name: eb-ms-pod-service
  labels:
    env: UAT-env
    app: eb-ms-app 
  namespace: uat #mention name space name which is  already created
spec:
  type: NodePort
  selector:
    app: eb-ms-app # production madle labels madle envoirnment variable chi name ahe ethe [app: eb-ms-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: httpp
      protocol: TCP
      port: 8080
      targetPort: 8080